name: Actions Workflow

on:
    #TRIGGERING MANUAL WORKFLOWS ON BRANCHES/TAGS & PATHS
    # push:
    #   branches:
    #     - master
    #     - 'feature/*'
    #     - 'feature/**'

    #     exclude
    #     - '!feature/featureC'

    #   tags:
    #     - v1./*

    #   paths:
    #     - '**.js'

    # triggering manual workflows // section 2 triggering workflows manually on udemy
    # change settings on github for token access
    # repository_dispatch:
    #    types: [build]

    # push:
    #schedule:
    #   - cron: '0/5 * * * *'
    #  - cron: '0/6 * * * *'
    pull_request:
        types: [closed, assigned, opened, reopened]

jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
            - name: List Files
              run: |
                  pwd
                  ls
            - name: Checkout
              uses: actions/checkout@v1
            - name: List Files After Checkout
              run: |
                  pwd
                  ls -a
            - name: simple JS actions
              id: greet
              uses: actions/hello-world-javascript-action@v1
              with:
                  who-to-greet: Future
            - name: Log Greeting time
              run: echo "${{ steps.greet.outputs.time }}"
